### ISSUE TITLE
Potential Trademark Issues

### ISSUE THREAD

**Issue by kallisti5** [HaikuTeam/core#11]
It's possible that *Haiku* might conflict with the trademarks of [Haiku, Inc.](http://haiku-inc.org) and [Haiku (the operating system)](http://haiku-os.org)

The similar Industry (Software) and similar branding could cause consumer confusion.
Haiku is proud of its branding and has enjoyed use of the trademark (registered and unregistered) since 2003. Haiku lives in the open-source ecosystem, so I'm posting this here publically to document our concerns.

**Comment by zackbrown** [comment]
Alex, thanks for your note.  We're big fans of the Haiku OS, and want to make sure that we're good neighbors.  We've both been inspired by the form of minimal poem that's our shared namesake, and I have to imagine we share some similar values as a result.

As we were just starting to build our brand and during the registration of our own trademark for HAIKU, I had an email exchange with one of your board members, Jessica Hamilton, about this.  Jessica pointed out that Haiku Inc.'s use and registration specifically covers "operating systems" — which is quite a bit different from the software industry as a whole or open source as a whole, both of which you mentioned here.  

A USPTO trademark search shows 55 live results for the HAIKU mark.  Of those 55, many involve computer software — Haiku by Epic, for example, is a very widely used piece of medical software.  On Github, a search for Haiku shows 2,153 open source software repositories.  Clearly there's room for more than one HAIKU in the software world, and even the open source world.

I want to reiterate that we have great respect for Haiku OS and the work that your team has done over the last decade and a half.

To keep our lawyers happy, I need to include the following snippet here as well:

> As established previously through correspondence between directors of our companies, Haiku Systems Inc.'s trademark for HAIKU is used in connection with distinguishable goods and services as compared to Haiku, Inc.'s use and registration.  As a result, there is no potential likelihood of confusion by consumers as to the source.  We consider this matter now closed, though naturally reserve our full rights with respect to this matter.

Please let me know if you have any questions or further thoughts.  If you'd like, you can reach me directly at zack@haiku.ai

Best regards,
Zack

**Comment by kallisti5** [comment]
Hey Zack,

Thanks for getting back to me.  Some background here, what spawned this was several community members asking me if we considered this a trademark conflict over the last few months.  I do think I remember Jessica mentioning speaking with a software project in the past about their trademark, but nothing ever got down on paper internally within the org with the details (and Jessica hasn't been around lately to provide me additional details)

I'll add some notes on this handshake agreement so we will have a clear answer if any community members bring it up again.

Thanks!

 -- Alexander von Gluck IV
