### ISSUE TITLE
We couldn't load the contents of ..

### ISSUE THREAD

**Issue by goldo** [HaikuTeam/core#2]
Hi, I'm trying to add sketch file or svg file without success on the mac app.
I'm having a: "We couldn't load the contents of designs/icon.svg" 

file is here: 
[icon_huit.svg.zip](https://github.com/HaikuTeam/core/files/1727406/icon_huit.svg.zip)

Thanks you

**Comment by nadonomy** [comment]
Hey @goldo,

Thanks for letting us know. Illustrator has some quirks in the way it exports SVG, but fortunately the settings for those are exposed. You should be able to import Illustrator assets to Haiku if you check the following options when exporting SVG (we tested here on Adobe CC 2017.1.0):

1. File > Export > Export As...
2. Choose Format: SVG (svg)
3. Optionally, select "Use Artboards"
4. In the next dialog box, choose **"Styling > Presentation Attributes"** and **"Object ID's > Unique"**, then ensure that **Minify** and **Responsive** are **NOT checked**

And the SVG's should be good to import using Haiku for Mac. 

I'm closing this issue as we have a fix planned for Haiku for Mac's codebase that will improve asset support. However, if you run into any more asset issues, feel free to [find us on Slack](https://join.slack.com/t/haiku-community/shared_invite/enQtMjU0NzExMzQzMjIxLTA3NjgzZDYzYmNjYzcxNmUwY2NhMTE0YTE2OGVjZGE0MDhmNGIxOWUzOTk5OTI5MmQ0ZjA5MDAwNGY1Yjk1OTg) or email me—  first 3 characters of my username [at] haiku [dot] ai. 

I've also made a note to improve our documentation on this issue.

Cheers,
Nad
