### ISSUE TITLE
PLEASE SUPPORT WINDOWS 10!

### ISSUE THREAD

**Issue by hamzaabdullah90** [HaikuTeam/core#5]

**Comment by nadonomy** [comment]
Hey @hamzaabdullah90,

We have Windows support for our desktop app in the pipeline for this year. To be amongst the first to know about when we ship, sign up at the form linked from here: [https://www.haiku.ai/windows-and-linux](https://www.haiku.ai/windows-and-linux).

Cheers,
Nad

**Comment by hamzaabdullah90** [comment]
Righ away, SIR!!
